export const stats_to_hash_map = {
    'NV_Robert Hero': 'rh',
    'BV_Dropped Him': 'dh',
    'BV_Hacking Success': 'hs',
    'NV_Robert Antihero': 'ra',
    'BV_Punt Him': 'ph',
    'BV_Bucket Success': 'bs',
    'BV_Attack Reporter': 'ar',
    'BV_Threw Water': 'tw',
    'BV_Kissed Blonde Blazer': 'kbb',
    'BV_Played Tutorial Well': 'ptw',
    'BV_Played Tutorial Poorly': 'ptp',
    'BV_AcceptableShiftRating': 'asr',
    'BV_102 Fist Bump Royd': 'fbr',
    'NV_RobertMentorCounter': 'rmc',
    'BV_Chose Disarm Granny': 'cdg',
    'BV_Kick Out Golem': 'kog',
    'BV_Cut Sonar': 'cs',
    'NV_SweetExitCounter': 'sec',
    'BV_Chose Waterboy': 'cw',
    'BV_Chose Invisigal': 'ci',
    'BV_Told Team Robert': 'ttr',
    'BV_Chose Beer': 'cb',
    'BV_Chose Twinkies': 'ct',
    "BV_She's gone": 'sg',
    'BV_Blamed Visi': 'bv',
    'BV_Leaned In': 'li',
    'BV_Said Track Star': 'sts',
    'BV_Glassed him': 'gh',
    'BV_Failed Last Dispatch': 'fld',
    'BV_Untie Invisigal': 'ui',
    'BV_Chose_ClusterBombs': 'ccb',
    'BV_Gave Both Pulses': 'gbp',
    'BV_Robert Killed Shroud': 'rks',
    'BV_Save ZTeamer': 'sz',
    'BV_104 Kissed Blazer': 'kb',
    'BV_BackedOutBlazer': 'bob'
}